export interface Picture {
    id: number,
    userId: number,
    url: string,
    title: string,
    descr: string,
    createdAt: string,
    takenAt: string,
    location: string,
    cameraModel: string,
    aperture: string,
    iso: number,
    focalLength: string,
    shutterSpeed: string,
}