services:
  web:
    container_name: Pixel_Webservice
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/storage
    environment:
      - NODE_ENV=development